@http = http://
@hostname = localhost
@port = 3000
@host = {{http}}{{hostname}}:{{port}}
@contentType = application/json
@endPoint = articles
@endPointLogin = signin

###
# @name login
POST {{host}}/{{endPointLogin}} HTTP/1.1
content-type: {{contentType}}

{
  "email": "brunojsampaio@gmail.com",
  "password": "123456"
}

###
@authToken = Bearer {{login.response.body.$.token}}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "10 motivos para usar VueJS",
  "description": "O artigo aborda os aspctos...",
  "userId": 1,
  "categoryId": 4,
  "content": "Conteúdo do artigo..."
}

###
GET {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

###
GET {{host}}/{{endPoint}}/1 HTTP/1.1
Authorization: {{authToken}}
content-type: {{contentType}}

###
PUT {{host}}/{{endPoint}}/1 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "10 motivos para usar VueJS",
  "description": "O artigo aborda os aspctos...",
  "userId": 1,
  "categoryId": 4,
  "content": "Conteúdo do artigo. alterado.."
}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Artigo para excluir",
  "description": "O artigo aborda os aspctos...",
  "userId": 1,
  "categoryId": 4,
  "content": "Conteúdo do artigo..."
}

###
DELETE {{host}}/{{endPoint}}/2 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}