@http = http://
@hostname = localhost
@port = 3000
@host = {{http}}{{hostname}}:{{port}}
@contentType = application/json
@endPoint = categories
@endPointLogin = signin

###
# @name login
POST {{host}}/{{endPointLogin}} HTTP/1.1
content-type: {{contentType}}

{
  "email": "brunojsampaio@gmail.com",
  "password": "123456"
}

###
@authToken = Bearer {{login.response.body.$.token}}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Web Moderno"
}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "CSS",
  "parentId": 1
}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "JS",
  "parentId": 1
}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "VueJS",
  "parentId": 3
}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Para alterar"
}

###
PUT {{host}}/{{endPoint}}/5 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Para excluir"
}

###
DELETE {{host}}/{{endPoint}}/5 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

###
GET {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

###
GET {{host}}/{{endPoint}}/1 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

###
GET {{host}}/{{endPoint}}/tree HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

###
GET {{host}}/{{endPoint}}/4/articles HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}