@http = http://
@hostname = localhost
@port = 3000
@host = {{http}}{{hostname}}:{{port}}
@contentType = application/json
@endPoint = users

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}

{
  "name": "Bruno Sampaio",
  "email": "brunojsampaio@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "admin": true
}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}

{
  "name": "Rakely Sampaio",
  "email": "rakelyribeiro@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "admin": false
}

###
GET {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}

###
GET {{host}}/{{endPoint}}/1 HTTP/1.1
content-type: {{contentType}}

###
PUT {{host}}/{{endPoint}}/1 HTTP/1.1
content-type: {{contentType}}

{
  "name": "Bruno Sampaio",
  "email": "brunojsampaio@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "admin": true
}