@http = http://
@hostname = localhost
@port = 3000
@host = {{http}}{{hostname}}:{{port}}
@contentType = application/json
@endPoint = users
@endPointLogin = signin

###
# @name login
POST {{host}}/{{endPointLogin}} HTTP/1.1
content-type: {{contentType}}

{
  "email": "brunojsampaio@gmail.com",
  # "email": "rakelyribeiro@gmail.com",
  "password": "123456"
}

###
@authToken = Bearer {{login.response.body.$.token}}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Bruno Sampaio",
  "email": "brunojsampaio@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "admin": true
}

###
POST {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Rakely Sampaio",
  "email": "rakelyribeiro@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "admin": false
}

###
GET {{host}}/{{endPoint}} HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

###
GET {{host}}/{{endPoint}}/1 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

###
PUT {{host}}/{{endPoint}}/1 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Bruno Sampaio",
  "email": "brunojsampaio@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "admin": true
}